vms/job/urls.py
from django.conf.urls import patterns, url
from job import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<job_id>\d+)$', views.delete, name='delete'),
    url(r'^details/(?P<job_id>\d+)$', views.details, name='details'),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<event_id>\d+)/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

vms/shift/urls.py
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)

vms/vms/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^job/', include('job.urls', namespace='job')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^shift/', include('shift.urls', namespace='shift')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
)

vms/shift/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from job.models import Job
from volunteer.models import Volunteer

class Shift(models.Model):
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    max_volunteers = models.IntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(5000)
        ]
    )
    #Job to Shift is a one-to-many relationship
    job = models.ForeignKey(Job)
    #VolunteerShift is the intermediary model for the many-to-many relationship between Volunteer and Shift
    volunteers = models.ManyToManyField(Volunteer, through='VolunteerShift')

class VolunteerShift(models.Model):
    #Volunteer  to VolunteerShift is a one-to-many relationship
    volunteer = models.ForeignKey(Volunteer)
    #Shift to VolunteerShift is a one-to-many relationship
    shift = models.ForeignKey(Shift)
    start_time = models.TimeField(blank=True, null=True)
    end_time = models.TimeField(blank=True, null=True)
    #assigned_by_manager = models.BooleanField()

vms/shift/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from shift.models import Shift

class HoursForm(forms.Form):
    start_time = forms.TimeField()
    end_time = forms.TimeField()

class ShiftForm(ModelForm):
    class Meta:
        model = Shift
        fields = ['date', 'start_time', 'end_time', 'max_volunteers']     

    #we don't check that start_time > end_time because we could 
    #start at 11pm and end at 1am and this test would fail

vms/shift/views.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from job.services import *
from shift.forms import HoursForm, ShiftForm
from shift.models import Shift
from shift.services import *
from volunteer.forms import SearchVolunteerForm
from volunteer.services import get_all_volunteers, search_volunteers

@login_required
def add_hours(request, shift_id, volunteer_id):
    if shift_id and volunteer_id:
        user = request.user
        if int(user.volunteer.id) == int(volunteer_id):
            if request.method == 'POST':
                form = HoursForm(request.POST)
                if form.is_valid():
                    start_time = form.cleaned_data['start_time']
                    end_time = form.cleaned_data['end_time']
                    try:
                        add_shift_hours(volunteer_id, shift_id, start_time, end_time)
                        return HttpResponseRedirect(reverse('shift:view_hours', args=(volunteer_id,)))
                    except:
                        raise Http404
                else:
                    return render(request, 'shift/add_hours.html', {'form' : form, 'shift_id' : shift_id, 'volunteer_id' : volunteer_id,})
            else:
                form = HoursForm()
                return render(request, 'shift/add_hours.html', {'form' : form, 'shift_id' : shift_id, 'volunteer_id' : volunteer_id,})
        else:
            return HttpResponse(status=403)
    else:
        raise Http404

#throwing an error when not signed in as administrator (will fix as the next task)
@login_required
def cancel(request, shift_id, volunteer_id):

    if shift_id and volunteer_id:

        user = request.user
        admin = None
        volunteer = None

        try:
            admin = user.administrator
        except ObjectDoesNotExist:
            pass
        try:
            volunteer = user.volunteer
        except ObjectDoesNotExist:
            pass

        #check that either an admin or volunteer is logged in
        if not admin and not volunteer:
            return HttpResponse(status=403)

        #if a volunteer is logged in, verify that they are canceling their own shift
        if volunteer:
            if (int(volunteer.id) != int(volunteer_id)):
                return HttpResponse(status=403)

        if request.method == 'POST':
            try:
                cancel_shift_registration(volunteer_id, shift_id)
                if admin:
                    return HttpResponseRedirect(reverse('shift:manage_volunteer_shifts', args=(volunteer_id,)))
                elif volunteer:
                    return HttpResponseRedirect(reverse('shift:view_volunteer_shifts', args=(volunteer_id,)))
                else:
                    raise Http404
            except:
                raise Http404
        else:
            return render(request, 'shift/cancel_shift.html', {'shift_id' : shift_id, 'volunteer_id' : volunteer_id})
    else:
        raise Http404

@login_required
def clear_hours(request, shift_id, volunteer_id):

    if shift_id and volunteer_id:
        if request.method == 'POST':
            result = clear_shift_hours(volunteer_id, shift_id)
            if result:
                return HttpResponseRedirect(reverse('shift:view_hours', args=(volunteer_id,)))
            else:
                raise Http404 
        else:
            return render(request, 'shift/clear_hours.html')
    else:
        raise Http404

@login_required
def create(request, job_id):
    if job_id:
        if request.method == 'POST':
            job = get_job_by_id(job_id)
            if job:
                form = ShiftForm(request.POST)
                if form.is_valid():
                    shift = form.save(commit=False)
                    shift.job = job
                    shift.save()
                    return HttpResponseRedirect(reverse('shift:list_shifts', args=(job_id,)))
                else:
                    return render(request, 'shift/create.html', {'form' : form, 'job_id' : job_id,})
            else:
                raise Http404
        else:
            form = ShiftForm()
            return render(request, 'shift/create.html', {'form' : form, 'job_id' : job_id,})
    else:
        raise Http404

@login_required
def delete(request, shift_id):

    if shift_id:
        if request.method == 'POST':
            result = delete_shift(shift_id)
            if result:
                return HttpResponseRedirect(reverse('shift:list_jobs'))
            else:
                return render(request, 'shift/delete_error.html')
        return render(request, 'shift/delete.html', {'shift_id' : shift_id})
    else:
        raise Http404

@login_required
def edit(request, shift_id):

    shift = None
    if shift_id:
        shift = get_shift_by_id(shift_id)

    if request.method == 'POST':
        form = ShiftForm(request.POST, instance=shift)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('shift:list_shifts', args=(shift.job.id,)))
        else:
            return render(request, 'shift/edit.html', {'form' : form, 'shift' : shift})
    else:
        form = ShiftForm(instance=shift)
        return render(request, 'shift/edit.html', {'form' : form, 'shift' : shift})

@login_required
def edit_hours(request, shift_id, volunteer_id):

    if shift_id and volunteer_id:
        volunteer_shift = get_volunteer_shift_by_id(volunteer_id, shift_id)
        user = request.user
        if int(user.volunteer.id) == int(volunteer_id):
            if volunteer_shift:
                if request.method == 'POST':
                    form = HoursForm(request.POST)
                    if form.is_valid():
                        start_time = form.cleaned_data['start_time']
                        end_time = form.cleaned_data['end_time']
                        try:
                            edit_shift_hours(volunteer_id, shift_id, start_time, end_time)
                            return HttpResponseRedirect(reverse('shift:view_hours', args=(volunteer_id,)))
                        except:
                            raise Http404
                    else:
                        return render(request, 'shift/edit_hours.html', {'form' : form, 'shift_id' : shift_id, 'volunteer_id' : volunteer_id})
                else:
                    form = HoursForm(initial={'start_time' : volunteer_shift.start_time, 'end_time' : volunteer_shift.end_time})
                    return render(request, 'shift/edit_hours.html', {'form' : form, 'shift_id' : shift_id, 'volunteer_id' : volunteer_id})
            else:
                raise Http404
        else:
            return HttpResponse(status=403)
    else:
        raise Http404

@login_required
def list_jobs(request):
    job_list = get_jobs_ordered_by_title()
    return render(request, 'shift/list_jobs.html', {'job_list' : job_list})

@login_required
def list_shifts(request, job_id):
    if job_id:
        job = get_job_by_id(job_id)
        if job:
            shift_list = get_shifts_ordered_by_date(job_id)
            return render(request, 'shift/list_shifts.html', {'shift_list' : shift_list, 'job_id' : job_id})
        else:
            raise Http404
    else:
        raise Http404

@login_required
def list_shifts_sign_up(request, job_id, volunteer_id):
    if job_id:
        job = get_job_by_id(job_id)
        if job:
            shift_list = get_shifts_with_open_slots(job_id)
            return render(request, 'shift/list_shifts_sign_up.html', {'shift_list' : shift_list, 'job' : job, 'volunteer_id' : volunteer_id})
        else:
            raise Http404
    else:
        raise Http404

@login_required
def manage_volunteer_shifts(request, volunteer_id):
    if volunteer_id:
        volunteer = get_volunteer_by_id(volunteer_id)
        if volunteer:
            #show only shifts that have no hours logged yet (since it doesn't make sense be able to cancel shifts that have already been logged)
            shift_list = get_unlogged_shifts_by_volunteer_id(volunteer_id)
            return render(request, 'shift/manage_volunteer_shifts.html', {'shift_list' : shift_list, 'volunteer_id' : volunteer_id})
        else:
            raise Http404
    else:
        raise Http404

@login_required
def sign_up(request, shift_id, volunteer_id):
    if shift_id:
        shift = get_shift_by_id(shift_id)
        if shift:

            user = request.user
            admin = None
            volunteer = None

            try:
                admin = user.administrator
            except ObjectDoesNotExist:
                pass
            try:
                volunteer = user.volunteer
            except ObjectDoesNotExist:
                pass

            if not admin and not volunteer:
                return HttpResponse(status=403)

            if volunteer:
                if (int(volunteer.id) != int(volunteer_id)):
                    return HttpResponse(status=403)

            if request.method == 'POST':
                try:
                    result = register(volunteer_id, shift_id)            
                    if result == "IS_VALID":
                        if admin:
                            return HttpResponseRedirect(reverse('shift:manage_volunteer_shifts', args=(volunteer_id,)))
                        if volunteer:
                            return HttpResponseRedirect(reverse('shift:view_volunteer_shifts', args=(volunteer_id,)))
                    else:
                        return render(request, 'shift/sign_up_error.html', {'error_code' : result})
                except ObjectDoesNotExist:
                    raise Http404
            else:
                return render(request, 'shift/sign_up.html', {'shift' : shift, 'volunteer_id' : volunteer_id})
        else:

vms/shift/templates/shift/add_hours.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <div class="well">
        <form class="form-horizontal" action="{% url 'shift:add_hours' shift_id volunteer_id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Log Shift Hours</legend>
                {% if form.start_time.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">Start Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="start_time" value="{% if form.start_time.value %}{{ form.start_time.value }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.start_time.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">Start Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="start_time" value="{% if form.start_time.value %}{{ form.start_time.value }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                {% if form.end_time.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">End Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="end_time" value="{% if form.end_time.value %}{{ form.end_time.value }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.end_time.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">End Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="end_time" value="{% if form.end_time.value %}{{ form.end_time.value }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                <div class="form-group">
                    <div class="col-md-12 col-md-offset-2">
                        <button class="btn btn-primary" type="submit">Submit</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

vms/shift/templates/shift/cancel_shift.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <form action="{% url 'shift:cancel' shift_id volunteer_id %}" method="post">
        {% csrf_token %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Cancel Shift Confirmation</h3>
            </div>
            <div class="panel-body">
                <br>
                {% if user.administrator %}
                    Are you sure you want to cancel this registered shift?
                {% else %}
                    Are you sure you want to cancel this shift you are signed up for?
                {% endif %}
                <br>
                <br>
                <button class="btn btn-danger" type="submit">Yes, Cancel this Shift</button>
                <input type="button" class="btn btn-default" value="Return to Previous Page" onClick="javascript:history.go(-1);">
            </div>
        </div>
    </form>
{% endblock %}

vms/shift/templates/shift/delete_error.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="alert alert-danger">
        <h4>Error</h4>
        <p>You cannot delete a shift that a volunteer has signed up for.</p>
        <br>
        <a href="{% url 'shift:list_jobs' %}" class="btn btn-default">Return to Previous Page</a>
    </div>
{% endblock %}

vms/shift/templates/shift/edit_hours.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <div class="well">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Edit Shift Hours</legend>
                {% if form.start_time.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">Start Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="start_time" value="{% if form.start_time.value %}{{ form.start_time.value|time:"H:i" }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.start_time.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">Start Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="start_time" value="{% if form.start_time.value %}{{ form.start_time.value|time:"H:i" }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                {% if form.end_time.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">End Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="end_time" value="{% if form.end_time.value %}{{ form.end_time.value|time:"H:i" }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.end_time.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">End Time</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="HH:MM" type="text" name="end_time" value="{% if form.end_time.value %}{{ form.end_time.value|time:"H:i" }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                <div class="form-group">
                    <div class="col-md-12 col-md-offset-2">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

vms/shift/templates/shift/hours_list.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <h3>Shift Hours</h3>
    <hr>
    {% if volunteer_shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Job</th>
                    <th>Date</th>
                    <th>Logged Start Time</th>
                    <th>Logged End Time</th>
                    <th>Edit Hours</th>
                    <th>Clear Hours</th>
                </tr>
            </thead>
            <tbody>
                {% for volunteershift in volunteer_shift_list %}
                    <tr>
                        <td>{{ volunteershift.shift.job.name }}</td>
                        <td>{{ volunteershift.shift.date }}</td>
                        <td>{{ volunteershift.start_time }}</td>
                        <td>{{ volunteershift.end_time }}</td>
                        <td>
                            <a href="{% url 'shift:edit_hours' volunteershift.shift.id user.volunteer.id %}" class="btn btn-info btn-sm">Edit Hours</a>
                        </td>
                        <td>
                            <a href="{% url 'shift:clear_hours' volunteershift.shift.id user.volunteer.id %}" class="btn btn-default btn-sm">Clear Hours</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            You have not logged any hours.
        </div>
    {% endif %}
{% endblock %}

vms/shift/templates/shift/list_shifts.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="well well-sm">
        <a href="{% url 'shift:create' job_id %}" class="btn btn-success btn-sm">Create Shift</a>
    </div>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Maximum # of Volunteers</th>
                <th>Edit</th>
                <th>Delete</th>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        <td>{{ shift.max_volunteers }}</td>
                        <td>
                            <a href="{% url 'shift:edit' shift.id %}" class="btn btn-info btn-sm">Edit</a>
                        </td>
                        <td>
                            <a href="{% url 'shift:delete' shift.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-success">
            There are currently no shifts. Please create shifts first.
        </div>
    {% endif %}            
{% endblock %}

vms/shift/templates/shift/list_shifts_sign_up.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <ul class="breadcrumb">
        <li><a href="{% url 'event:list_sign_up' volunteer_id %}">Events</a></li>
        <li><a href="{% url 'job:list_sign_up' job.event.id volunteer_id %}">{{ job.event.name }} Jobs</a></li>
        <li class="active">{{ job.name }} Shifts</li>
    </ul>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Start Time</th>
                    <th>End Time</th>
                    {% if user.administrator %}
                        <th>Assign Shift</th>
                    {% else %}
                        <th>Sign Up</th>
                    {% endif %}
                    <th>Slots Remaining</th>
                </tr>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        {% if user.administrator %}
                            <td>
                                <a href="{% url 'shift:sign_up' shift.id volunteer_id %}" class="btn btn-success btn-sm">Assign Shift</a>
                            </td>
                        {% else %}
                            <td>
                                <a href="{% url 'shift:sign_up' shift.id volunteer_id %}" class="btn btn-success btn-sm">Sign Up</a>
                            </td>
                        {% endif %}
                        <td>{{ shift.slots_remaining }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            There are currently no shifts for the {{ job.name }} job.
        </div>
    {% endif %}
{% endblock %}

vms/shift/templates/shift/manage_volunteer_shifts.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <a href="{% url 'shift:volunteer_search' %}" class="btn btn-default">Return to Volunteer Search</a>
    <div class="spacer"></div>
    <h3>Manage Shifts</h3>
    <hr>
    <div class="well well-sm">
        <a href="{% url 'event:list_sign_up' volunteer_id %}" class="btn btn-success btn-sm">Assign Shift</a>
    </div>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <th>Job</th>
                <th>Date</th>
                <th>Scheduled Start Time</th>
                <th>Scheduled End Time</th>
                <th>Cancel Shift Registration</th>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.job.name }}</td>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        <td>
                            <a href="{% url 'shift:cancel' shift.id volunteer_id %}" class="btn btn-danger btn-sm">Cancel Shift Registration</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            This volunteer does not have any upcoming shifts.
        </div>
    {% endif %}
{% endblock %}

vms/shift/templates/shift/sign_up_error.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <div class="alert alert-danger">
        <h4>Error</h4>
        <br>
        {% if error_code == "ERROR_CODE_ALREADY_SIGNED_UP" %}
            {% if user.administrator %}
                This user is already signed up for this shift. Please assign a different shift.
            {% else %}
                You have already signed up for this shift. Please sign up for a different shift.
            {% endif %}
        {% elif error_code == "ERROR_CODE_NO_SLOTS_REMAINING" %}
            {% if user.administrator %}
                There are no slots remaining for this shift. Please assign a different shift.
            {% else %}
                There are no slots remaining for this shift. Please sign up for a different shift.
            {% endif %}
        {% else %}
        {% endif %}
        <br>
        <br>
        <input type="button" class="btn btn-default" value="Return to Previous Page" onClick="javascript:history.go(-1);">
    </div>
{% endblock %}

vms/shift/templates/shift/volunteer_shifts.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <h3>Upcoming Shifts</h3>
    <hr>
    {% if shift_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Job</th>
                    <th>Date</th>
                    <th>Scheduled Start Time</th>
                    <th>Scheduled End Time</th>
                    <th>Log Hours</th>
                    <th>Cancel Shift Registration</th>
                </tr>
            </thead>
            <tbody>
                {% for shift in shift_list %}
                    <tr>
                        <td>{{ shift.job.name }}</td>
                        <td>{{ shift.date }}</td>
                        <td>{{ shift.start_time }}</td>
                        <td>{{ shift.end_time }}</td>
                        <td>
                            <a href="{% url 'shift:add_hours' shift.id user.volunteer.id %}" class="btn btn-success btn-sm">Log Hours</a>
                        </td>
                        <td>
                            <a href="{% url 'shift:cancel' shift.id user.volunteer.id %}" class="btn btn-danger btn-sm">Cancel Shift Registration</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            You do not have any upcoming shifts.
        </div>
    {% endif %}
{% endblock %}