vms/event/urls.py
from django.conf.urls import patterns, url
from event import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<event_id>\d+)$', views.delete, name='delete'),
    url(r'^edit/(?P<event_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

vms/job/urls.py
from django.conf.urls import patterns, url
from job import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<job_id>\d+)$', views.delete, name='delete'),
    url(r'^details/(?P<job_id>\d+)$', views.details, name='details'),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<event_id>\d+)/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

vms/shift/urls.py
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)

vms/vms/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^job/', include('job.urls', namespace='job')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^shift/', include('shift.urls', namespace='shift')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
)

vms/event/models.py
from django.core.validators import RegexValidator
from django.db import models

class Event(models.Model):
    name = models.CharField(
        max_length=75,
        validators=[
            RegexValidator(
                r'^[(A-Z)|(a-z)|(0-9)|(\s)|(\.)|(,)|(\-)|(!)]+$',
            ),
        ],
    )
    start_date = models.DateField()
    end_date = models.DateField()

vms/event/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm
from event.models import Event

class EventForm(ModelForm):
    class Meta:
        model = Event
        fields = ['name', 'start_date', 'end_date']
    
    def clean(self):

        start_date = self.cleaned_data.get('start_date')
        end_date = self.cleaned_data.get('end_date')

        if start_date and end_date:
            if start_date > end_date:
                msg = u"Start date must be before the end date"
                self._errors['start_date'] = self.error_class([msg])

        return self.cleaned_data

vms/event/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from event.forms import EventForm
from event.services import *

@login_required
def create(request):

    if request.method == 'POST':
        form = EventForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('event:list'))
        else:
            return render(request, 'event/create.html', {'form' : form,})
    else:
        form = EventForm()
        return render(request, 'event/create.html', {'form' : form,})

@login_required
def delete(request, event_id):

    if request.method == 'POST':
        result = delete_event(event_id)
        if result:
            return HttpResponseRedirect(reverse('event:list'))
        else:
            return render(request, 'event/delete_error.html')
    return render(request, 'event/delete.html', {'event_id' : event_id})

@login_required
def edit(request, event_id):

    event = None
    if event_id:
        event = get_event_by_id(event_id)

    if request.method == 'POST':
        form = EventForm(request.POST, instance=event)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('event:list'))
        else:
            return render(request, 'event/edit.html', {'form' : form,})
    else:
        form = EventForm(instance=event)
        return render(request, 'event/edit.html', {'form' : form,})

@login_required
def list(request):
    event_list = get_events_ordered_by_name()
    return render(request, 'event/list.html', {'event_list' : event_list})

@login_required
def list_sign_up(request, volunteer_id):
    event_list = get_events_ordered_by_name()
    return render(request, 'event/list_sign_up.html', {'event_list' : event_list, 'volunteer_id' : volunteer_id})

vms/event/templates/event/create.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="well">
        <form class="form-horizontal" action="{% url 'event:create' %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Create Event</legend>
                {% if form.name.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">Event Name</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="Event Name" type="text" name="name" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.name.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">Event Name</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="Event Name" type="text" name="name" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                {% if form.start_date.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">Start Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="start_date" value="{% if form.start_date.value %}{{ form.start_date.value }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.start_date.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">Start Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="start_date" value="{% if form.start_date.value %}{{ form.start_date.value }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                {% if form.end_date.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">End Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="end_date" value="{% if form.end_date.value %}{{ form.end_date.value }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.end_date.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">End Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="end_date" value="{% if form.end_date.value %}{{ form.end_date.value }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                <div class="form-group">
                    <div class="col-md-12 col-md-offset-2">
                        <button class="btn btn-primary" type="submit">Create</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

vms/event/templates/event/delete.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <form class="form-horizontal" action="{% url 'event:delete' event_id %}" method="post">
        {% csrf_token %}
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Delete Event</h3>
            </div>
            <div class="panel-body">
                Are you sure you want to delete this event?
                <br>
                <br>
                <button class="btn btn-default" type="submit">Yes, Delete this Event</button>
                <a href="{% url 'event:list' %}" class="btn btn-default">No</a>
            </div>
        </div>
    </form>
{% endblock %}

vms/event/templates/event/delete_error.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="alert alert-danger">
        <h4>Error</h4>
        <p>You cannot delete an event that a job is currently associated with.</p>
        <br>
        <a href="{% url 'event:list' %}" class="btn btn-default">Return to Previous Page</a>
    </div>
{% endblock %}

vms/event/templates/event/edit.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="well">
        <form class="form-horizontal" action="" method="post">
            {% csrf_token %}
            <fieldset>
                <legend>Edit Event</legend>
                {% if form.name.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">Event Name</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="Event Name" type="text" name="name" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.name.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">Event Name</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="Event Name" type="text" name="name" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                {% if form.start_date.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">Start Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="start_date" value="{% if form.start_date.value %}{{ form.start_date.value|date:"SHORT_DATE_FORMAT" }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.start_date.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">Start Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="start_date" value="{% if form.start_date.value %}{{ form.start_date.value|date:"SHORT_DATE_FORMAT" }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                {% if form.end_date.errors %}
                    <div class="form-group has-error">
                        <label class="col-md-2 control-label">End Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="end_date" value="{% if form.end_date.value %}{{ form.end_date.value|date:"SHORT_DATE_FORMAT" }}{% endif %}">
                            <p class="help-block">
                                <strong>
                                    {% for error in form.end_date.errors %}
                                        {{ error }}
                                    {% endfor %}
                                </strong>
                            </p>
                        </div>
                    </div>
                {% else %}
                    <div class="form-group">
                        <label class="col-md-2 control-label">End Date</label>
                        <div class="col-md-8">
                            <input class="form-control" placeholder="MM/DD/YYYY" type="text" name="end_date" value="{% if form.end_date.value %}{{ form.end_date.value|date:"SHORT_DATE_FORMAT" }}{% endif %}">
                        </div>
                    </div>
                {% endif %}
                <div class="form-group">
                    <div class="col-md-12 col-md-offset-2">
                        <button class="btn btn-primary" type="submit">Save</button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
{% endblock %}

vms/event/templates/event/list.html
{% extends "administrator/settings.html" %}

{% block setting_content %}
    <div class="spacer"></div>
    <div class="well well-sm">
        <a href="{% url 'event:create' %}" class="btn btn-success btn-sm">Create Event</a>
    </div>
    {% if event_list %}
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Event Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for event in event_list %}
                    <tr>
                        <td>{{ event.name }}</td>
                        <td>{{ event.start_date }}</td>
                        <td>{{ event.end_date }}</td>
                        <td>
                            <a href="{% url 'event:edit' event.id %}" class="btn btn-info btn-sm">Edit</a>
                        </td>
                        <td>
                            <a href="{% url 'event:delete' event.id %}" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-success">
            There are currently no events. Please create events first.
        </div>
    {% endif %}
{% endblock %}

vms/event/templates/event/list_sign_up.html
{% extends "vms/base.html" %}

{% block content %}
    <div class="spacer"></div>
    <a href="{% url 'shift:manage_volunteer_shifts' volunteer_id %}" class="btn btn-default">Return to Manage Shifts</a>
    <div class="spacer"></div>
    {% if event_list %}
        <ul class="breadcrumb">
            <li class="active">Events</li>
        </ul>
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Event Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>View Jobs</th>
                </tr>
            </thead>
            <tbody>
                {% for event in event_list %}
                    <tr>
                        <td>{{ event.name }}</td>
                        <td>{{ event.start_date }}</td>
                        <td>{{ event.end_date }}</td>
                        <td>
                            <a href="{% url 'job:list_sign_up' event.id volunteer_id %}" class="btn btn-success btn-sm">View Jobs</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <div class="alert alert-info">
            There are currently no events.
        </div>
    {% endif %}
{% endblock %}