vms/home/urls.py
from django.conf.urls import patterns, url
from home import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
)

vms/job/urls.py
from django.conf.urls import patterns, url
from job import views

urlpatterns = patterns('',
    url(r'^create/$', views.create, name='create'),
    url(r'^delete/(?P<job_id>\d+)$', views.delete, name='delete'),
    url(r'^details/(?P<job_id>\d+)$', views.details, name='details'),
    url(r'^edit/(?P<job_id>\d+)$', views.edit, name='edit'),
    url(r'^list/$', views.list, name='list'),
    url(r'^list_sign_up/(?P<event_id>\d+)/(?P<volunteer_id>\d+)$', views.list_sign_up, name='list_sign_up'),
)

vms/registration/urls.py
from django.conf.urls import patterns, url
from registration import views

urlpatterns = patterns('',
    url(r'^signup_administrator/$', views.signup_administrator, name='signup_administrator'),
    url(r'^signup_volunteer/$', views.signup_volunteer, name='signup_volunteer'),
)

vms/shift/urls.py
from django.conf.urls import patterns, url
from shift import views

urlpatterns = patterns('',
    url(r'^add_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.add_hours, name='add_hours'),
    url(r'^create/(?P<job_id>\d+)$', views.create, name='create'),
    url(r'^cancel/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.cancel, name='cancel'),
    url(r'^delete/(?P<shift_id>\d+)$', views.delete, name='delete'),
    url(r'^clear_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.clear_hours, name='clear_hours'),
    url(r'^edit/(?P<shift_id>\d+)$', views.edit, name='edit'),
    url(r'^edit_hours/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.edit_hours, name='edit_hours'),
    url(r'^list_jobs/$', views.list_jobs, name='list_jobs'),
    url(r'^list_shifts/(?P<job_id>\d+)$', views.list_shifts, name='list_shifts'),
    url(r'^list_shifts_sign_up/(?P<job_id>\d+)/(?P<volunteer_id>\d+)$', views.list_shifts_sign_up, name='list_shifts_sign_up'),
    url(r'^manage_volunteer_shifts/(?P<volunteer_id>\d+)$', views.manage_volunteer_shifts, name='manage_volunteer_shifts'),
    url(r'^sign_up/(?P<shift_id>\d+)/(?P<volunteer_id>\d+)$', views.sign_up, name='sign_up'),
    url(r'^view_hours/(?P<volunteer_id>\d+)$', views.view_hours, name='view_hours'),
    url(r'^view_volunteer_shifts/(?P<volunteer_id>\d+)$', views.view_volunteer_shifts, name='view_volunteer_shifts'),
    url(r'^volunteer_search/$', views.volunteer_search, name='volunteer_search'),
)

vms/vms/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^administrator/', include('administrator.urls', namespace='administrator')),
    url(r'^authentication/', include('authentication.urls', namespace='authentication')),
    url(r'^event/', include('event.urls', namespace='event')),
    url(r'^home/', include('home.urls', namespace='home')),
    url(r'^job/', include('job.urls', namespace='job')),
    url(r'^organization/', include('organization.urls', namespace='organization')),
    url(r'^registration/', include('registration.urls', namespace='registration')),
    url(r'^shift/', include('shift.urls', namespace='shift')),
    url(r'^volunteer/', include('volunteer.urls', namespace="volunteer")),
)

vms/volunteer/urls.py
from django.conf.urls import patterns, url
from volunteer import views

urlpatterns = patterns('',
    url(r'^delete_resume/(?P<volunteer_id>\d+)$', views.delete_resume, name='delete_resume'),
    url(r'^download_resume/(?P<volunteer_id>\d+)$', views.download_resume, name='download_resume'),
    url(r'^edit/(?P<volunteer_id>\d+)$', views.edit, name='edit'),
    url(r'^profile/(?P<volunteer_id>\d+)$', views.profile , name='profile'),
    url(r'^report/(?P<volunteer_id>\d+)$', views.report, name='report'),
    url(r'^search/$', views.search, name='search'),
)

vms/vms/templates/vms/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Volunteer Management System</title>
    <!-- Bootstrap core CSS -->
    <!--<link href="../../static/vms/bootstrap-3.2.0-dist/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="{% static "vms/bootstrap-lumen-theme/css/bootstrap.min.css" %}" rel="stylesheet">
    <!-- Custom styling taken from Systers Portal -->
    <link href="{% static "vms/css/style.css" %}" rel="stylesheet">
    <link href="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.min.css" %}" rel="stylesheet">
    <link href="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.structure.min.css" %}" rel="stylesheet">
    <link href="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.theme.min.css" %}" rel="stylesheet">
    <script src="{% static "vms/jquery/jquery-1.11.1.min.js" %}"></script>
    <script src="{% static "vms/bootstrap-3.2.0-dist/js/bootstrap.min.js" %}"></script>
    <script src="{% static "vms/jquery-ui-1.11.4.custom/jquery-ui.min.js" %}"></script>
    <script src="{% static "vms/jquery-custom/activate-datepicker.js" %}"></script>
  </head>
  <body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'home:index' %}">Systers</a>
            </div>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav text-uppercase">
                    <li><a href="#">About</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right text-uppercase">
                    {% if user.is_authenticated %}
                        {% if user.administrator %}
                            <li><a href="{% url 'volunteer:search' %}">Volunteer Search</a></li>
                            <li><a href="{% url 'shift:volunteer_search' %}">Manage Volunteer Shifts</a></li>
                            <li><a href="{% url 'administrator:report' %}">Report</a></li>
                            <li><a href="{% url 'administrator:settings' %}">Settings</a></li>
                            <li><a href="{% url 'registration:signup_administrator' %}">Create Admin Account</a></li>
                        {% endif %}
                        {% if user.volunteer %} 
                            <li><a href="{% url 'shift:view_volunteer_shifts' user.volunteer.id %}">Upcoming Shifts</a></li>
                            <li><a href="{% url 'shift:view_hours' user.volunteer.id %}">Shift Hours</a></li>
                            <li><a href="{% url 'event:list_sign_up' user.volunteer.id %}">Shift Sign Up</a></li>
                            <li><a href="{% url 'volunteer:report' user.volunteer.id %}">Report</a></li>
                            <li><a href="{% url 'volunteer:profile' user.volunteer.id %}">Profile</a></li>
                        {% endif %}
                        <li><a href="{% url 'authentication:logout_process' %}">Log Out</a></li>
                    {% else %}
                        <li><a href="{% url 'registration:signup_volunteer' %}">Sign Up</a></li>
                        <li><a href="{% url 'authentication:login_process' %}">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>